printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: all

overrides:
- files: "*.scss"
  options:
    parser: scss
    tabWidth: 4
    singleQuote: false
- files: "*.json"
  options:
    tabWidth: 4
    singleQuote: false
